name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [main]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest ]
        env:
            DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        steps:
            -   uses: actions/checkout@v4.1.6
            -   uses: actions/setup-node@v4
                with:
                    node-version: 18
            -   run: npm install -g @datadog/datadog-ci
            -   name: Set DD env tag
                run: DATADOG_SITE=datadoghq.com datadog-ci tag --level pipeline --tags env:dev
            -   name: Set up JDK 21
                uses: actions/setup-java@v4.2.1
                with:
                    distribution: 'temurin'
                    java-version: 21
                    architecture: x64
            -   name: Cache Maven packages
                uses: actions/cache@v4.0.2
                with:
                    path: ~/.m2
                    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                    restore-keys: ${{ runner.os }}-m2-
            -   name: Build with Maven
                run: |
                    if [ "$RUNNER_OS" == "macOS" ]; then
                        # Make "localhost" DNS entry available; see https://github.com/actions/runner-images/issues/6383
                        # sudo networksetup -setdnsservers Ethernet 9.9.9.9
                        echo -e "$(ipconfig getifaddr en0) $(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
                        echo `sudo lsof -PiTCP -sTCP:LISTEN`
                        cat /etc/hosts
                        mvn --no-transfer-progress verify -DskipTests -DwaittimeForServerStart=150
                        # skip tests on macos, takes too long with the current runners
                    else
                        mvn --no-transfer-progress verify -DwaittimeForServerStart=30
                    fi
                shell: bash
            -   name: Get Project Version from pom.xml
                uses: entimaniac/read-pom-version-action@1.0.0
                id: getVersion
            -   name: Set DD version tag
                run: DATADOG_SITE=datadoghq.com datadog-ci tag --level pipeline --tags version:${{ steps.getVersion.outputs.version }}
